be-oi/beoi.be-oi.be

- config.rb
- data/faq/nl.yml
- data/tasks.yml
- locales/fr.yml
- locales/nl.yml
- source/layouts/layout.erb
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
- source/localizable/_index_contest_training.fr.html.erb
- source/localizable/_index_contest_training.nl.html.erb
- source/localizable/_index_list_categories.fr.html.erb
- source/localizable/_index_list_categories.nl.html.erb
- source/localizable/_rules_contestflow.fr.html.erb
- source/localizable/_rules_contestflow.nl.html.erb
- source/localizable/_rules_introduction.fr.html.erb
- source/localizable/_rules_introduction.nl.html.erb
- source/localizable/_rules_participants.fr.html.erb
- source/localizable/_rules_participants.nl.html.erb
- source/localizable/faq.html.erb
- source/localizable/index.html.erb
- source/localizable/rules.html.erb
- source/localizable/tasks/_social_network.fr.md
- source/localizable/tasks/_social_network.nl.md
- source/localizable/tasks/_south_pole.fr.md
- source/localizable/tasks/_south_pole.nl.md
> everything ready to be release (minimal version) in fr

- locales/fr.yml
- locales/nl.yml
- source/localizable/index.html.erb
> mailing list to be informed about registration opening. 

- data/faq/fr.yml
- data/faq/nl.yml
> faq for schools

- locales/fr.yml
- locales/nl.yml
- source/localizable/index.html.erb
- source/localizable/registration.html.erb
> link to registration

- config.rb
- data/faq/fr.yml
- data/faq/nl.yml
- data/qualification_centers.yml
- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/index.html.erb
very few translation needed in nl
> qualif-round centers with a map

- locales/fr.yml
- locales/nl.yml
- source/localizable/index.html.erb
> new black message on home page: beOI17 and qualif results

- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
Small first updates for beOI 17. Can be merged when translated.
> update dates for beOI17

- locales/fr.yml
- locales/nl.yml
- source/localizable/about.html.erb
FR text is to be reviewed in fr.yml .
> added a link to our KBS - FRB sponsoring page

- data/sponsors.yml
- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/index.html.erb
- source/localizable/registration.html.erb
@jganseman Please translate the few sentences as soon as possible so that we can start opening the registration as soon as possible... (already 1/4 of December...)
> Registration17

- data/results_2017_final.yml
- source/localizable/final_results.html.erb
Modifications pour affichage des classements et scores complets de la finale beOI 2017.
@smadbe
> Final be oi2017 ludovic g

- locales/fr.yml
- locales/nl.yml
- source/localizable/registration.html.erb
one sentence to be translated to nl
> add info on top of the registration form

- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
Schedules FR and NL for the 2019 final.
> Ludovic g patch 1

- config.rb
- data/results_2019_final.yml
- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
- source/localizable/_index_final_sample_questions.html.erb
- source/localizable/final_results.html.erb
- source/localizable/index.html.erb
Branch final2019_results to merge.
> Results final 2019.

- data/qualification_centers.yml
Could not test it, `bundle install` fails on my machine at the moment.
> Add Charleroi qualification centre

- config.rb
- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_calendar.html.erb
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.fr.html.erb.bak
- source/localizable/_index_contest_step1.nl.html.erb
- source/localizable/_index_contest_step1.nl.html.erb.bak
- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.fr.html.erb.bak
- source/localizable/_index_contest_step2.nl.html.erb
- source/localizable/_index_contest_step2.nl.html.erb.bak
Dates for launching beOI 2022.
No archive yet for previous year.
On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
modified:   ../../config.rb
modified:   ../../locales/fr.yml
modified:   ../../locales/nl.yml
modified:   _index_calendar.html.erb
renamed:    _index_contest_step1.fr.html.erb.bak -> _index_contest_step1.fr.html.erb
renamed:    _index_contest_step1.fr.html.erb -> _index_contest_step1.fr.html.erb.bak
renamed:    _index_contest_step1.nl.html.erb.bak -> _index_contest_step1.nl.html.erb
renamed:    _index_contest_step1.nl.html.erb -> _index_contest_step1.nl.html.erb.bak
modified:   _index_contest_step2.fr.html.erb
modified:   _index_contest_step2.fr.html.erb.bak
modified:   _index_contest_step2.nl.html.erb
modified: …
> Website updated to launch beOI year 2021-2022.

- source/localizable/_index_calendar.html.erb
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
Added link to training platform.
> Calendar correction.

- data/qualification_centers.yml
Most addresses were already commented, so this commit only updates Charleroi information (change of place and commenting address out).
> Comment addresses of qualitifaction centerss

- data/qualification_centers.yml
- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_contest_step1.fr.html.erb
- source/localizable/_index_contest_step1.nl.html.erb
Disable empty centres so that we can free involved people.
> Empty centres

- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
Add place of the final (ULB Paul-Emile-Janson)
> Reveal place of the final (ULB - Paul-Emile-Janson)

- data/members.yml
Howest paid their 2020-2021 fee on 27/1/2022; UHasselt and Vives did not pay
> members.yml: +Howest, -UHasselt, -Vives

- source/localizable/_index_contest_step2.fr.html.erb
- source/localizable/_index_contest_step2.nl.html.erb
- source/localizable/about.html.erb
Adress, date, TIME and infos for the 2023 final.
> update board members.

- source/localizable/_index_enter_becp.fr.html.erb
- source/localizable/_index_enter_becp.nl.html.erb
Explicit C++ requirement for beCP + fix typos in French beCP page.
> Explicit C++ requirement for beCP

- source/localizable/_index_calendar.html.erb
The dates have just been announced on https://ejoi2024.gov.md/
> Add dates for EJOI 2024

- locales/fr.yml
- locales/nl.yml
- source/localizable/_index_calendar.html.erb
Has the dates for WEOI and IOI
> calendar update
